name: macOS Build Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@master
    - uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl_src
    - name: brew
      run: brew install automake libtool

    - name: wolfssl autogen
      working-directory: ./wolfssl_src
      run: ./autogen.sh
    - name: wolfssl configure
      working-directory: ./wolfssl_src
      run: ./configure --enable-wolfclu --enable-crl --enable-dsa --enable-pkcs7 --prefix=$GITHUB_WORKSPACE/build-dir
    - name: wolfssl make
      working-directory: ./wolfssl_src
      run: make
    - name: wolfssl make install
      working-directory: ./wolfssl_src
      run: make install

    - name: Check wolfSSL install dir
      run: ls $GITHUB_WORKSPACE/build-dir

    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-wolfssl=$GITHUB_WORKSPACE/build-dir
    - name: make
      run: make
    - name: make check
      run: make check
    - name: display log
      if: always()
      run: cat test-suite.log
